metadata:
  configurationMountPath: /opt/proxy_config
  developerPop:
    opsVariables:
      - name: SECTION_OPS_LOG_LEVEL
        value: debug
  httpContainer: perimeterx
  image: gcr.io/section-io/perimeterx:1.0.0-k1
  logs:
    additional:
      - container: perimeterx
        name: error.log
        stream: stderr
    handler: perimeterx
    http:
      container: perimeterx
      stream: stdout
  name: perimeterx:1.0.0
spec:
  containers:
    - name: perimeterx
      resources:
        limits:
          memory: 100Mi
        requests:
          memory: 15Mi
